[package]
name = "telegram-bot-rest-client"
version = "1.0.0"
authors = ["Eugene Lebedev <duke.tougu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

log = "0.4.8"
log4rs = "0.10.0"